spring:
  profiles:
    include:
      - filter
      - jwt
  application:
    name: backend

  security:
    user:
      name: user
      password: 1234

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB


logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            security: ERROR
        data:
          repository:
            config:
              RepositoryConfigurationExtensionSupport: ERROR


management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

server:
  shutdown: graceful
